module(
    name = "rules_mobile_assets",
    version = "0.0.5",
)

bazel_dep(name = "platforms", version = "1.1.0")
bazel_dep(name = "bazel_skylib", version = "1.8.2")
bazel_dep(name = "aspect_bazel_lib", version = "2.22.5")

bazel_dep(name = "rules_rs", version = "0.0.100", dev_dependency = True)
bazel_dep(name = "llvm", version = "0.8.21", dev_dependency = True)

toolchains = use_extension("@rules_rs//rs/toolchains:module_extension.bzl", "toolchains", dev_dependency = True)
toolchains.toolchain(
    edition = "2024",
    version = "1.92.0",
)
use_repo(toolchains, "default_rust_toolchains")

# This extension is optional but can help keep existing `@rules_rust` references working.
rules_rust = use_extension("@rules_rs//rs:rules_rust.bzl", "rules_rust", dev_dependency = True)
use_repo(rules_rust, "rules_rust")

register_toolchains(
    "@default_rust_toolchains//...",
    "@llvm//toolchain:all",
    dev_dependency = True
)

crate = use_extension("@rules_rs//rs:extensions.bzl", "crate", dev_dependency = True)
crate.from_cargo(
    name = "i",
    cargo_lock = "//tools/resizer:Cargo.lock",
    cargo_toml = "//tools/resizer:Cargo.toml",
    platform_triples = [
        "aarch64-apple-darwin",
        "aarch64-pc-windows-msvc",
        "aarch64-unknown-linux-gnu",
        "x86_64-apple-darwin",
        "x86_64-pc-windows-msvc",
        "x86_64-unknown-linux-gnu",
    ],
)
use_repo(crate, "i")

bazel_dep(name = "apple_support", version = "2.6.1", dev_dependency = True, repo_name = "build_bazel_apple_support")
bazel_dep(name = "stardoc", version = "0.8.1", dev_dependency = True)
